### ISSUE TITLE
Predict的时候会出现问题！！！！请问有大佬遇到过吗？

### ISSUE THREAD

**Issue by Wzyblur** [yangjianxin1/ClipCap-Chinese#10]
Traceback (most recent call last):
  File "/home/ai/wzy/Code/ClipCap-Chinese-master/predict.py", line 190, in <module>
    main(args)
  File "/home/ai/wzy/Code/ClipCap-Chinese-master/predict.py", line 148, in main
    clip_embeds = clip_model.encode_image(images)
  File "/home/ai/wzy/Hugging_face/CLIP-main/clip/model.py", line 341, in encode_image
    return self.visual(image.type(self.dtype))
  File "/home/ai/anaconda3/envs/pyTorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/wzy/Hugging_face/CLIP-main/clip/model.py", line 224, in forward
    x = self.conv1(x)  # shape = [*, width, grid, grid]
  File "/home/ai/anaconda3/envs/pyTorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ai/anaconda3/envs/pyTorch/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ai/anaconda3/envs/pyTorch/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)

**Comment by babyta** [comment]
143行后加，images = images.cuda()
captions = generate(model.half(), clip_embeds, tokenizer, args)
这行也得改
