### ISSUE TITLE
AttributeError: type object 'GPT2LMHeadModel' has no attribute 'from_config'

### ISSUE THREAD

**Issue by funykatebird** [yangjianxin1/ClipCap-Chinese#6]
raceback (most recent call last):
  File "ClipCap-Chinese-master/models/model.py", line 75, in __init__
    self.gpt2 = GPT2LMHeadModel.from_pretrained(gpt2_path)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1222, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index', 'flax_model.msgpack'] found in directory pretrain_models/gpt2 or `from_tf` and `from_flax` set to False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ClipCap-Chinese-master/train.py", line 150, in <module>
    main(args)
  File "/ClipCap-Chinese-master/train.py", line 114, in main
    model = ClipCaptionModel(
  File "/ClipCap-Chinese-master/models/model.py", line 79, in __init__
    self.gpt2 = GPT2LMHeadModel.from_config(config)
AttributeError: type object 'GPT2LMHeadModel' has no attribute 'from_config'

**Comment by funykatebird** [comment]
可直接修改为加载GPT2LMHeadModel.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
然后下载对应的模型文件
https://huggingface.co/uer/gpt2-chinese-cluecorpussmall/tree/main

**Comment by funykatebird** [comment]
一般就是数据和模型一个在cpu，一个在GPU
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu
方法一：
args.device = torch.device("cpu")

方法二：
将数据加载到GPU上
images = images.to(args.device)
                clip_embeds = clip_model.encode_image(images)
        # clip_embeds = clip_embeds.unsqueeze(1).repeat(1, args.num_generate, 1).view(-1, clip_embeds.size(-1))
        clip_embeds = clip_embeds.unsqueeze(1).repeat(1, args.num_generate, 1).view(-1, clip_embeds.size(-1)).float()

**Comment by yywhsgnd** [comment]
(env1) jupyter@task_3050_yangyuwei:~/workspace/ClipCap-Chinese-master$ python3 predict.py
2022-12-28 11:48:11.682 | INFO     | models.model:__init__:80 - random initialize gpt2 model
Traceback (most recent call last):
  File "predict.py", line 186, in <module>
    main(args)
  File "predict.py", line 129, in main
    model.load_state_dict(torch.load(args.model_path, map_location=args.device))
  File "/home/jupyter/miniforge3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jupyter/miniforge3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jupyter/miniforge3/envs/env1/lib/python3.7/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/mlp_finetune/checkpoint-35000.pt'

**Comment by minimumcat** [comment]
顶，好帖子，谢谢楼主

**Comment by qq123aa456** [comment]
改为加载GPT2LMHeadModel.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
然后下载对应的模型文件之后出现错误，
Can't set hidden_size with value 768 for GPT2Config {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 50256,
  "eos_token_id": 50256,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "model_type": "gpt2",
  "pad_token_id": 0
}

Can't set hidden_size with value 768 for GPT2Config {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 50256,
  "eos_token_id": 50256,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "model_type": "gpt2",
  "pad_token_id": 0
}

Traceback (most recent call last):
  File "/data/lpj/caca/models/model.py", line 74, in __init__
    self.gpt2 = GPT2LMHeadModel.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/modeling_utils.py", line 876, in from_pretrained
    **kwargs,
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 330, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 417, in from_dict
    config = cls(**config_dict)
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_gpt2.py", line 150, in __init__
    super().__init__(bos_token_id=bos_token_id, eos_token_id=eos_token_id, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 221, in __init__
    raise err
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 218, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 150, in <module>
    main(args)
  File "train.py", line 116, in main
    args.finetune_gpt2, args.constant_len
  File "/data/lpj/caca/models/model.py", line 77, in __init__
    config = GPT2LMHeadModel.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/modeling_utils.py", line 876, in from_pretrained
    **kwargs,
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 330, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 417, in from_dict
    config = cls(**config_dict)
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_gpt2.py", line 150, in __init__
    super().__init__(bos_token_id=bos_token_id, eos_token_id=eos_token_id, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 221, in __init__
    raise err
  File "/home/user/anaconda3/lib/python3.6/site-packages/transformers/configuration_utils.py", line 218, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute
有没有人知道是为什么？
